args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "4",
  "-device",
  "virtio-blk-device,drive=disk0",
  "-append",
  "root=/dev/vda rw init=/bin/sh",
  "-m",
  "8g",
]
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
  "(?i)kernel panic",
  "(?i)login incorrect",
  "(?i)permission denied",
]
success_regex = ["(?m)^test pass!\\s*$"]
shell_prefix = "~ #"
shell_init_cmd = "pwd && echo 'test pass!'"
to_bin = true
uefi = false
